#!/bin/bash
## start up workflow! =)
## 11-04-2012 pdq

# truecrypt mounted success file
filea="/media/truecrypt1/test"
fileb="/media/truecrypt2/test"

# formatting
txtbld=$(tput bold)             # Bold
bldred=${txtbld}$(tput setaf 1) # Red Colored
bldgreen=${txtbld}$(tput setaf 2) # Green Colored
bldblue=${txtbld}$(tput setaf 6) # Blue Colored
bldyellow=${txtbld}$(tput setaf 3) # Yellow Colored
txtrst=$(tput sgr0)             # Reset

if [ -f "$filea" ] ; then
	echo "${bldblue}[SKIP] It appears your primary data is already mounted, proceeding to secondary data...${txtrst}"
else
	echo "${bldred}[WAIT] Decrypt primary data and proceed to desktop session${txtrst}"
	truecrypt /home/pdq/vital/hiddenfiles /media/truecrypt1
	if [ -f "$filea" ] ; then
		echo "${bldgreen}mounted /media/truecrypt1${txtrst}"
	else
		echo "${bldred}Incorrect passphrase...exiting${txtrst}"
		exit
	fi
fi
if [ "$(pidof xbindkeys)" ] ; then
	echo "${bldblue}[SKIP] xbindkeys already running, skipping${txtrst}"
else
	echo "${bldgreen}[OK] Starting xbindkeys (custom keyboard shortcuts)...${txtrst}"
	xbindkeys
fi
if [ -f "$fileb" ] ; then
	echo "${bldblue}[SKIP] It appears your secondary data is already mounted, proceeding to desktop session...${txtrst}"
else
	echo "${bldred}[WAIT] Decrypt secondary data and proceed to desktop session${txtrst}"
	truecrypt /media/HDD2p/pdq/vital/hiddenfiles2 /media/truecrypt2
	if [ -f "$fileb" ] ; then
		echo "${bldgreen}mounted /media/truecrypt2${txtrst}"
	else
		echo "${bldred}Incorrect passphrase...exiting${txtrst}"
		exit
	fi
fi
echo "${bldgreen}[OK] Starting pdq desktop session...${txtrst}"
wmctrl -s 0
sleep 1s
if [ "$(pidof luakit)" ] ; then
	echo "${bldblue}[SKIP] Web browsers already running, skipping${txtrst}"
else
	echo "${bldgreen}[OK] Starting web browsers...${txtrst}"
	luakit > /dev/null 2>&1 &
	luakit -c ~/.config/luakit/rc-proxy.lua > /dev/null 2>&1 &
fi
if [ "$(pidof bitlbee)" ] ; then
	echo "${bldblue}[SKIP] bitlbee already running, skipping${txtrst}"
else
	echo "${bldgreen}[OK] Starting Instant Messaging server...${txtrst}"
	sudo bitlbee -D
fi
if [ "$(pidof httpd)" ] ; then
	echo "${bldblue}[SKIP] LAMP may already be running, restarting${txtrst}"
	sudo lamp restart
else
	echo "${bldgreen}[OK] Starting LAMP server...${txtrst}"
	sudo lamp start
fi
echo "${bldgreen}[OK] Restoring desktop wallpaper and system information display...${txtrst}"
nitrogen --restore &
if [ "$(pidof conky)" ] ; then
	killall conky
fi
sh ~/.config/awesome/global_script.sh > /dev/null 2>&1
if [ "$(pidof weechat-curses)" ] ; then
	echo "${bldblue}[SKIP] IRC clients already running, skipping${txtrst}"
else
	echo "${bldgreen}[OK] Starting IRC clients...${txtrst}"
	urxvtc -e weechat-curses &
	urxvtc -e weechat-curses -d ~/.weechat-priv &
fi
if [ "$(pidof vlc)" ] ; then
	echo "${bldblue}[SKIP] Video player already running, skipping${txtrst}"
else
	echo "${bldgreen}[OK] Starting video player and playing playlist...${txtrst}"
	vlc ~/Videos/tempvideo > /dev/null 2>&1 &

fi
if [ "$(pidof transmission-qt)" ] ; then
	echo "${bldblue}[SKIP]Torrent client already running, skipping${txtrst}"
else
	echo "${bldgreen}[OK] Starting torrent client...${txtrst}"
	transmission-qt > /dev/null 2>&1 &
fi
if [ "$(pidof sublime_text)" ] ; then
	echo "${bldblue}[SKIP] Text editors already running, skipping${txtrst}"
else
	echo "${bldgreen}[OK] Starting text editors...${txtrst}"
	subl
	sudo subl
fi
echo "${bldgreen}[OK] Starting terminals...${txtrst}"
wmctrl -s 2
sleep 1s
urxvtc -name logging -e sudo journalctl -f &
urxvtc -name arm -e arm &
urxvtc -name debug -e tail -f ~/.cache/awesome/stderr &
if [ "$(pidof dolphin)" ] ; then
	echo "${bldblue}[SKIP]File manager already running, skipping${txtrst}"
else
	echo "${bldgreen}[OK] Starting file manager...${txtrst}"
	dolphin > /dev/null 2>&1 & 
fi
if [ "$(pidof keepassx)" ] ; then
	echo "${bldblue}Password manager already running, skipping${txtrst}"
else
	keepassx &
fi
wmctrl -s 6
sleep 1s
if [ "$(pidof mocp)" ] ; then
	echo "${bldblue}[SKIP] Music server and client already running, restarting${txtrst}"
	killall mocp
	urxvtc -e mocp &
else
	echo "${bldgreen}[OK] Starting music server and client...${txtrst}"
	urxvtc -e mocp &
fi
wmctrl -r "tail" -t 2
wmctrl -r "arm" -t 2
wmctrl -r "sudo" -t 2
wmctrl -r "moc" -t 6
wmctrl -r "weechat" -t 1
wmctrl -r "vlc" -t 5
wmctrl -r "playlist" -t 5
wmctrl -r "/home/pdq/pdq-db.kdb" -t 5
wmctrl -r "dolphin" -t 5
sleep 1s
wmctrl -r "playlist" -b toggle,hidden
wmctrl -r "dolphin" -b toggle,hidden
wmctrl -s 5
urxvtc &
echo "${bldblue}[ACTIVE] Workflow restoration completed... SEE YA!${txtrst}"
#sleep 2s
echo "${bldgreen}[EXITING]${txtrst}"
#sleep 2s
exit
