#!/bin/bash
# pacman update
echo ":: updating system..."
echo "sudo pacman -Syu"
sudo pacman -Syu
echo " "
echo ":: update complete..."
echo " "
sleep 2s
echo ":: this window will automatically close after 15 minutes"
echo ":: ctrl+c to manually exit"
notify-send "pacman" \
            "Update complete" \
            -i /usr/share/icons/kAwOkenDark/clear/22x22/apps/pacman.png
sleep 15m
exit